Update readme to include new SPI subsets + SPI wishlist
DynamicsAndNeuralSystems/pyspi_tmp pull request #2
Opened 2023-07-21 20:31 UTC by anniegbryant

2023-08-02 00:46 UTC, anniegbryant commented
@benfulcher ready for your review now, this amends the subset syntax and directs users to the projects tab to suggest new SPIs

2023-08-07 01:54 UTC, benfulcher commented on README.md
> +Oliver M. Cliff, Annie G. Bryant, Joseph T. Lizier, Naotsugu Tsuchiya, Ben D. Fulcher, "Unifying Pairwise Interactions in Complex Dynamics," _arXiv_ preprint, [arXiv:2201.11941v2](https://arxiv.org/a
If you leave off the 'v2' from the URL then it takes to the most recent version. This is preferable

2023-08-07 01:54 UTC, benfulcher commented on README.md
> +As _pyspi_ is under active development, we are always open to suggestions for new SPIs to be added via the [projects tab](https://github.com/DynamicsAndNeuralSystems/pyspi/projects) in this repo.
Ooh cool idea—is it functional?

2023-08-07 01:56 UTC, benfulcher commented on pyspi/calculator.py
>                  configfile = os.path.dirname(os.path.abspath(__file__)) + "/config.yaml"
Imagine a user mis-spelling say 'fabfive'. Can you catch this instance with an appropriate message? E.g., "there is no feature subset named 'fabfive', …"

2023-08-07 01:56 UTC, benfulcher requested changes
A few minor comments—can be addressed pretty trivially…

2023-08-07 02:31 UTC, anniegbryant commented on README.md
> +As _pyspi_ is under active development, we are always open to suggestions for new SPIs to be added via the [projects tab](https://github.com/DynamicsAndNeuralSystems/pyspi/projects) in this repo.
Yep (kinda)! Check it out -- https://github.com/orgs/DynamicsAndNeuralSystems/projects/2

2023-08-07 02:33 UTC, anniegbryant commented on pyspi/calculator.py
>                  configfile = os.path.dirname(os.path.abspath(__file__)) + "/config.yaml"
Added

2023-08-07 03:56 UTC, benfulcher commented on pyspi/calculator.py
>                  configfile = os.path.dirname(os.path.abspath(__file__)) + "/config.yaml"
I don't mean fabfive explicitly, but any key that isn't in the current set of valid subset names

2023-08-07 03:57 UTC, benfulcher commented on pyspi/calculator.py
>                  configfile = os.path.dirname(os.path.abspath(__file__)) + "/config.yaml"
This is the last pending change

2023-08-07 03:57 UTC, benfulcher requested changes
Make catch for invalid subset string more general

2023-08-08 05:45 UTC, merged